server:
  port: 80

spring:
  application:
    name: consumer
dubbo:
  application:
    name: consumerApplication
  registry:
      address: zookeeper://${zookeeper.address:127.0.0.1}:2181

management:
  endpoints:
    web:
      exposure:
        include: mappings,health,info
